name: Deploy site to GitHub Pages

on:
  push:
    branches: [ main, update-design-for-elevate ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  packages: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          
      - name: Configure npm authentication
        run: |
          echo "@inform-elevate:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=\${NODE_AUTH_TOKEN}" >> ~/.npmrc

      - name: Test authentication
        run: |
          echo "Testing GitHub Package Registry authentication..."
          npm whoami --registry=https://npm.pkg.github.com || echo "Authentication test failed"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ELEVATE_NPM_TOKEN }}

      - name: Install dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ELEVATE_NPM_TOKEN }}

      - name: Build with Gatsby
        run: npm run build -- --prefix-paths
        env:
          NODE_ENV: production
          CI: true
          GATSBY_BUILD: true
          GATSBY_CPU_COUNT: 2

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
