name: Deploy site to GitHub Pages

on:
  push:
    branches: [ main, update-design-for-elevate ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  packages: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'
          
      - name: Validate ELEVATE_NPM_TOKEN
        run: |
          if [ -z "${{ secrets.ELEVATE_NPM_TOKEN }}" ]; then
            echo "❌ ELEVATE_NPM_TOKEN secret is empty or not set"
            echo "Please add a valid GitHub Personal Access Token to repository secrets"
            exit 1
          else
            echo "✅ ELEVATE_NPM_TOKEN secret is present"
            # Test if it's a valid token format (should start with ghp_ or github_pat_)
            if [[ "${{ secrets.ELEVATE_NPM_TOKEN }}" =~ ^(ghp_|github_pat_) ]]; then
              echo "✅ Token format appears valid"
            else
              echo "⚠️  Warning: Token format may be invalid (should start with ghp_ or github_pat_)"
            fi
          fi

      - name: Configure authentication for yarn
        run: |
          echo "@inform-elevate:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.ELEVATE_NPM_TOKEN }}" >> ~/.npmrc
          
      - name: Test authentication
        run: |
          echo "Testing GitHub Package Registry authentication..."
          npm whoami --registry=https://npm.pkg.github.com || echo "Authentication test failed"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ELEVATE_NPM_TOKEN }}

      - name: Install dependencies with yarn
        run: yarn install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ELEVATE_NPM_TOKEN }}

      - name: Build with Gatsby
        run: yarn build --prefix-paths
        env:
          NODE_ENV: production
          CI: true
          GATSBY_BUILD: true
          GATSBY_CPU_COUNT: 2

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
