name: Deploy site to GitHub Pages

on:
  push:
    branches: [ main, update-design-for-elevate ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  packages: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@inform-elevate'

      - name: Debug authentication
        run: |
          echo "ELEVATE_NPM_TOKEN exists: ${{ secrets.ELEVATE_NPM_TOKEN != '' }}"
          echo "Using token source: ${{ secrets.ELEVATE_NPM_TOKEN != '' && 'ELEVATE_NPM_TOKEN' || 'GITHUB_TOKEN' }}"
          
      - name: Install dependencies
        run: |
          # Try to install with authentication first
          if npm install; then
            echo "✅ Successfully installed with private packages"
          else
            echo "❌ Failed to install private packages, trying fallback..."
            # Remove private packages temporarily and install public packages only
            npm pkg delete dependencies.@inform-elevate/elevate-cdk
            npm pkg delete dependencies.@inform-elevate/elevate-core-ui  
            npm pkg delete dependencies.@inform-elevate/elevate-design-tokens
            npm pkg delete dependencies.@inform-elevate/elevate-icons
            echo "Installing without private packages..."
            npm install
            echo "⚠️  WARNING: Built without ELEVATE private packages!"
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ELEVATE_NPM_TOKEN || secrets.GITHUB_TOKEN }}

      - name: Build with Gatsby
        run: npm run build -- --prefix-paths
        env:
          NODE_ENV: production
          CI: true
          GATSBY_BUILD: true
          GATSBY_CPU_COUNT: 2

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
