name: Deploy site to GitHub Pages

on:
  push:
    branches: [ main, update-design-for-elevate ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
  packages: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@inform-elevate'

      - name: Configure npm for GitHub Packages
        run: |
          # Configure npm registry for @inform-elevate scope
          echo "@inform-elevate:registry=https://npm.pkg.github.com" >> ~/.npmrc
          
          # Use GITHUB_TOKEN with proper permissions
          echo "Using GITHUB_TOKEN for authentication"
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc
          export NODE_AUTH_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          
          # Test authentication (optional - may fail but shouldn't stop build)
          echo "Testing authentication..."
          npm whoami --registry=https://npm.pkg.github.com || echo "Authentication test failed but continuing..."
          
          echo "GATSBY_BUILD=true" >> $GITHUB_ENV

      - name: Install dependencies
        run: |
          # Set the correct NODE_AUTH_TOKEN
          export NODE_AUTH_TOKEN="${{ secrets.GITHUB_TOKEN }}"
          
          echo "Installing dependencies with authentication..."
          
          # Install dependencies
          if yarn install; then
            echo "✅ Successfully installed all dependencies including private packages"
            yarn list --pattern "@inform-elevate/*" || echo "No private packages found"
          else
            echo "❌ Failed to install dependencies"
            exit 1
          fi

      - name: Build with Gatsby
        run: yarn build --prefix-paths
        env:
          NODE_ENV: production
          CI: true
          GATSBY_BUILD: true
          GATSBY_CPU_COUNT: 2

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
